---
title: "Data Cleaning"
author: "Jiashu Liu, Jingdan Zou & Qihan Chen"
date: "5/07/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load("/Users/jiashuliu/Desktop/ML&2004/Messy Data/Final_Project/Messy_Data_Final/NSDUH_2021.RData")
load("/Users/zjd/Desktop/nyu/Messy data ML/Final/NSDUH_2021.RData")
```

```{r}
#Loading libraries
library(tidyverse)
library(httr)
library(jsonlite)
library(foreach)
```

```{r}
#Outcome variable
NSDUH_2021_full <- PUF2021_100622 %>%
  mutate(across(c("udmjlrgamts", "udmjnotstop", "udmjtimeget", 
                  "udmjwantbad", "udmjworkprb", "udmjfmlyprb",
                  "udmjfmlyctd", "udmjstopact", "udmjgethurt", 
                  "udmjmntlctd", "udmjhlthctd", "udmjneedmor", 
                  "udmjlesseff", "udmjwdangry", "udmjwdflanx", 
                  "udmjwdsleep", "udmjwdappet", "udmjwdsitst", 
                  "udmjwddeprs", "udmjwdstmch", "udmjwdshake", 
                  "udmjwdsweat", "udmjwdfever", "udmjwdchill", 
                  "udmjwdhedac", "udmjavwmarj", "udmjstrurge", 
                  "udmjwdshake"), 
                ~if_else(. %in% c(83, 85, 91, 94, 97, 98, 99), 0,
                         if_else(. == 1, 1, 0)))) %>%
  mutate(SUD_MJ = rowSums(select(., c("udmjlrgamts", "udmjnotstop", "udmjtimeget", 
                                       "udmjwantbad", "udmjworkprb", "udmjfmlyprb",
                                       "udmjfmlyctd", "udmjstopact", "udmjgethurt", 
                                       "udmjmntlctd", "udmjhlthctd", "udmjneedmor", 
                                       "udmjlesseff", "udmjwdangry", "udmjwdflanx", 
                                       "udmjwdsleep", "udmjwdappet", "udmjwdsitst", 
                                       "udmjwddeprs", "udmjwdstmch", "udmjwdshake", 
                                       "udmjwdsweat", "udmjwdfever", "udmjwdchill", 
                                       "udmjwdhedac", "udmjavwmarj", "udmjstrurge", 
                                       "udmjwdshake"))) >= 2, 
         SUD_MJ = if_else(SUD_MJ, 1, 0))

```

```{r}
#Predictors
# record variables
# 1) age (1=Adolescent: 18-, 2=Young Adult: 18-30, 3=Middle Age: 30-50, 4=Elderly: 50+)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(age = case_when(AGE3 %in% c(1:3) ~ 1,
                         AGE3 %in% c(4:8) ~ 2,
                         AGE3 %in% c(9:10) ~ 3,
                         TRUE ~ 4))

# 2) sex (0=Female, 1=Male)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(sex = if_else(irsex == 2,0,1))

# 3) race (1=white, 2=non-white, 3=Hispanic)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(race = case_when(NEWRACE2 %in% c(2:6) ~ 2,
                          NEWRACE2 == 7 ~ 3,
                          TRUE ~ 1))

# 4) health (0=w/o health problem: excellent/very good/good, 1=with health problem: fair/poor)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(health = case_when(health %in% c(1:3) ~ 0,
                            health %in% c(4:5) ~ 1,
                            TRUE ~ NA))

# 5) marital (0=never been married/cannot married<=14, 1=married, 2=widowed/divorced/separated),
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(marital = case_when(irmarit %in% c(4,99) ~ 0,
                             irmarit %in% c(2:3) ~ 2,
                             TRUE ~ 1))

# 6) degree (1=w/o high school, 2=high school degree, 3=associate's degree/college graduate or higher)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(degree = case_when(IREDUHIGHST2 %in% c(1:7) ~ 1,
                            IREDUHIGHST2 %in% c(8:9) ~ 2,
                            TRUE ~ 3))

# 7) eduskip (days missed school from skipping, 99~'no class', 'unknown') 
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(eduskip = case_when(eduskpest == 1 ~ 0,
                              eduskpest == 2 ~ 1,
                              eduskpest == 3 ~ 2,
                              eduskpest == 4 ~ 4,
                              eduskpest == 5 ~ 18,
                              eduskpmon %in% c(85,94,97,98) ~ NA,
                              TRUE ~ eduskpmon))
# NOTE: eduskip incorporates data from EDUSKPMON (if respondents reported a valid number of days
#that they missed school in QD21) or EDUSKPEST (if respondents were asked question QD21DKRE 
#because they answered QD21 as "don't know" or "refused"). 
#If respondents reported in QD21DKRE that they missed school on "3 to 5 days" or on "6 or more 
#days," then EDUSKPCOM was assigned the value at the midpoint in the range (i.e., 4 days or 18 days, respectively).
```

```{r}
# 8) employ (1=employed full time, 2=employed part time, 3=unemployed, 4=Other(incl. not in labor force))
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(employ = case_when(WRKSTATWK2 %in% c(1,6) ~ 1,
                            WRKSTATWK2 %in% c(2:3) ~ 2,
                            WRKSTATWK2 %in% c(4,9) ~ 3,
                            TRUE ~ 4))

# 9) persons in Household (range 1-5, 6=6 or more people in household)
NSDUH_2021_full <- NSDUH_2021_full %>% mutate(family = IRHHSIZ2)

# 10) kids age<18 in Household (range 0-2, 3=3 or more people in household)
NSDUH_2021_full <- NSDUH_2021_full %>% mutate(kid = IRKI17_2-1)

# 11) elderly age>65 in Household (range 0-1, 2=2 or more people in household)
NSDUH_2021_full <- NSDUH_2021_full %>% mutate(elderly = IRHH65_2-1)
```

```{r}
# 12) covid_mh: how covid-19 negatively affected mental health (0=otherwise, 1=not at all, 2=a little/some, 3=quite a bit/lot )
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(covid_mh = case_when(conegmh == 1 ~ 1,
                              conegmh %in% c(2:3) ~ 2,
                              conegmh %in% c(4:5) ~ 3,
                              TRUE ~ 0))

# 13) covid_fin: how often serious financial worries due covid (0=otherwise, 1=never, 2=some/rarely, 3=very often)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(covid_fin = case_when(cofinanc == 5 ~ 1,
                               cofinanc %in% c(3:4) ~ 2,
                               cofinanc %in% c(1:2) ~ 3,
                               TRUE ~ 0))

# 14) health_insur (0=w/o health insurance, 1=health insurance)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(health_insur = case_when(irmedicr == 1 | irmcdchp ==1 | irchmpus==1 | 
                                    irprvhlt==1 | irothhlt == 1 ~ 1,
                                  TRUE ~ 0))

```

```{r}
# 15) income: family income (1=poverty:20000-, 2=middle:74999-, 3=wealth:75000+)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(income = case_when(IRFAMIN3 %in% c(1:2) ~ 1,
                            IRFAMIN3 %in% c(3:6) ~ 2,
                            TRUE ~ 3))

# 16) assist: receive assist payment (0=w/o assist, 1=in one/more assist)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(assist = case_when(irfamsoc == 1 | irfamssi ==1 | irfstamp ==1 | 
                              irfampmt ==1 | irfamsvc == 1 ~ 1,
                               TRUE ~ 0))

# 17) county (0=rural, 1=urban)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(county = case_when(COUTYP4 %in% c(1:2) ~ 1,
                            TRUE ~ 0))

# 18) aia: American Indian area (0=not in AIAs, 1=in AIAs)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(aia = if_else(MAIIN102 == 2,0,1))

# 19) pregnant (0=otherwise, 1=yes)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(pregnant = if_else(pregnant == 2,0,1))

# 20) BMI (range=9.3733333333 - 68.557024793)
NSDUH_2021_full <- NSDUH_2021_full %>% mutate(bmi = BMI2)
```

```{r}
# 21) schfeel: feeling about go to school(0=otherwise, 1=didn't like/hate, 2=like)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(schfeel = case_when(yeschflt %in% c(3:4) ~ 1,
                             yeschflt %in% c(1:2) ~ 2,
                             TRUE ~ 0))

# 22) parhw: parent check/help homework(0=otherwise, 1=seldom, 2=always)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(parhw = case_when(yepchkhw %in% c(3:4) | yephlphw %in% c(3:4) ~ 1,
                           yepchkhw %in% c(1:2) | yephlphw %in% c(1:2) ~ 2,
                           TRUE ~ 0))

# 23) mentalhealth: combined score of K6 questions (range = 0 - 24, na:Aged 12-17)
NSDUH_2021_full <- NSDUH_2021_full %>% 
  mutate(k1 = case_when(IRDSTCHR30 == 1 ~ 4,
                         IRDSTCHR30 == 2 ~ 3,
                         IRDSTCHR30 == 3 ~ 2,
                         IRDSTCHR30 == 4 ~ 1,
                         IRDSTCHR30 == 5 ~ 0,
                         TRUE ~ 99),
         k2 = case_when(IRDSTEFF30 == 1 ~ 4,
                         IRDSTEFF30 == 2 ~ 3,
                         IRDSTEFF30 == 3 ~ 2,
                         IRDSTEFF30 == 4 ~ 1,
                         IRDSTEFF30 == 5 ~ 0,
                         TRUE ~ 99),
         k3 = case_when(IRDSTHOP30 == 1 ~ 4,
                         IRDSTHOP30 == 2 ~ 3,
                         IRDSTHOP30 == 3 ~ 2,
                         IRDSTHOP30 == 4 ~ 1,
                         IRDSTHOP30 == 5 ~ 0,
                         TRUE ~ 99),
         k4 = case_when(IRDSTNGD30 == 1 ~ 4,
                         IRDSTNGD30 == 2 ~ 3,
                         IRDSTNGD30 == 3 ~ 2,
                         IRDSTNGD30 == 4 ~ 1,
                         IRDSTNGD30 == 5 ~ 0,
                         TRUE ~ 99),
         k5 = case_when(IRDSTNRV30 == 1 ~ 4,
                         IRDSTNRV30 == 2 ~ 3,
                         IRDSTNRV30 == 3 ~ 2,
                         IRDSTNRV30 == 4 ~ 1,
                         IRDSTNRV30 == 5 ~ 0,
                         TRUE ~ 99),
         k6 = case_when(IRDSTRST30 == 1 ~ 4,
                         IRDSTRST30 == 2 ~ 3,
                         IRDSTRST30 == 3 ~ 2,
                         IRDSTRST30 == 4 ~ 1,
                         IRDSTRST30 == 5 ~ 0,
                         TRUE ~ 99),
         mentalhealth = case_when(k1 == 99 | k2 == 99 | k3 == 99 | k4 == 99 | 
                                    k5 == 99 | k6 == 99 ~  NA,
                                  TRUE ~ k1+k2+k3+k4+k5+k6))
    
# For each of the six items listed above, responses of "all of the time" were coded 4, 
#"most of the time" were coded 3, "some of the time" were coded 2, "a little of the time" 
#were coded 1, and "none of the time" were coded 0. These assigned values were summed 
#across the six items to calculate a total score for mentalhealth.

```
```{r}
# select relevant variables
NSDUH_2021 <- NSDUH_2021_full %>%
  select(age, sex, race, health, marital, degree, eduskip, employ, family, kid, 
         elderly, covid_mh, covid_fin, health_insur, income, assist, county, aia, 
         pregnant, bmi, schfeel, parhw, mentalhealth, SUD_MJ)

```

```{r}
# check NAs
NSDUH_2021 %>% summarise_all(list(name = ~sum(is.na(.))/length(.)))
```

```{r}
write_csv(NSDUH_2021, "NSDUH_2021.csv")
```

